name: Build TDLib
on:
    workflow_dispatch:
        inputs:
            tdlib:
                description: "TDLib git ref (e.g. v1.8.0 or a commit hash)"
                type: string
                required: true
# NOTE: The ZLIB_USE_STATIC_LIBS option requires CMake >= 3.24
jobs:
    build:
        name: Build TDLib on  x86_64 Ubuntu 18.04 (glibc)
        runs-on: ubuntu-18.04
        steps:
            - uses: actions/checkout@v3
              with:
                  repository: "tdlib/td"
                  ref: ${{ inputs.tdlib }}
            - name: Install gperf
              run: sudo apt install -y -q gperf
            - name: Build TDLib
              run: |
                  mkdir -p build && cd build
                  cmake -DCMAKE_BUILD_TYPE=Release \
                    -DOPENSSL_USE_STATIC_LIBS=TRUE -DZLIB_USE_STATIC_LIBS=TRUE ..
                  cmake --build . --target tdjson -- -j 2
                  cd ..
            - name: Strip
              run: strip build/libtdjson.so
            - name: Info
              run: |
                  uname -a
                  cmake --version
                  openssl version
                  ldd --version
                  ldd build/libtdjson.so
            - uses: actions/upload-artifact@v3
              with:
                  name: libtdjson.so
                  path: build/libtdjson.so
